// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: language.proto

package com.linwei.cams.datastore.protobuf;

public interface LanguagePreferencesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LanguagePreferences)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string locale = 1;</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string locale = 1;</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();
}
