// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: language.proto

package com.linwei.cams.datastore.protobuf;

public final class Language {
  private Language() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
