// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projecttree.proto

package com.linwei.cams.datastore.protobuf;

/**
 * Protobuf type {@code ProjectTreePreferences}
 */
public  final class ProjectTreePreferences extends
    com.google.protobuf.GeneratedMessageLite<
        ProjectTreePreferences, ProjectTreePreferences.Builder> implements
    // @@protoc_insertion_point(message_implements:ProjectTreePreferences)
    ProjectTreePreferencesOrBuilder {
  private ProjectTreePreferences() {
    projectTreeBean_ = emptyProtobufList();
  }
  public interface ProjectTreeBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProjectTreePreferences.ProjectTreeBean)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string children = 1;</code>
     * @return A list containing the children.
     */
    java.util.List<java.lang.String>
        getChildrenList();
    /**
     * <code>repeated string children = 1;</code>
     * @return The count of children.
     */
    int getChildrenCount();
    /**
     * <code>repeated string children = 1;</code>
     * @param index The index of the element to return.
     * @return The children at the given index.
     */
    java.lang.String getChildren(int index);
    /**
     * <code>repeated string children = 1;</code>
     * @param index The index of the element to return.
     * @return The children at the given index.
     */
    com.google.protobuf.ByteString
        getChildrenBytes(int index);

    /**
     * <code>int32 courseId = 2;</code>
     * @return The courseId.
     */
    int getCourseId();

    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 order = 5;</code>
     * @return The order.
     */
    int getOrder();

    /**
     * <code>int32 parentChapterId = 6;</code>
     * @return The parentChapterId.
     */
    int getParentChapterId();

    /**
     * <code>bool userControlSetTop = 7;</code>
     * @return The userControlSetTop.
     */
    boolean getUserControlSetTop();

    /**
     * <code>int32 visible = 8;</code>
     * @return The visible.
     */
    int getVisible();
  }
  /**
   * Protobuf type {@code ProjectTreePreferences.ProjectTreeBean}
   */
  public  static final class ProjectTreeBean extends
      com.google.protobuf.GeneratedMessageLite<
          ProjectTreeBean, ProjectTreeBean.Builder> implements
      // @@protoc_insertion_point(message_implements:ProjectTreePreferences.ProjectTreeBean)
      ProjectTreeBeanOrBuilder {
    private ProjectTreeBean() {
      children_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      name_ = "";
    }
    public static final int CHILDREN_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> children_;
    /**
     * <code>repeated string children = 1;</code>
     * @return A list containing the children.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated string children = 1;</code>
     * @return The count of children.
     */
    @java.lang.Override
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated string children = 1;</code>
     * @param index The index of the element to return.
     * @return The children at the given index.
     */
    @java.lang.Override
    public java.lang.String getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated string children = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the children at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChildrenBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          children_.get(index));
    }
    private void ensureChildrenIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          children_;  if (!tmp.isModifiable()) {
        children_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated string children = 1;</code>
     * @param index The index to set the value at.
     * @param value The children to set.
     */
    private void setChildren(
        int index, java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureChildrenIsMutable();
      children_.set(index, value);
    }
    /**
     * <code>repeated string children = 1;</code>
     * @param value The children to add.
     */
    private void addChildren(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  ensureChildrenIsMutable();
      children_.add(value);
    }
    /**
     * <code>repeated string children = 1;</code>
     * @param values The children to add.
     */
    private void addAllChildren(
        java.lang.Iterable<java.lang.String> values) {
      ensureChildrenIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, children_);
    }
    /**
     * <code>repeated string children = 1;</code>
     */
    private void clearChildren() {
      children_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string children = 1;</code>
     * @param value The bytes of the children to add.
     */
    private void addChildrenBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureChildrenIsMutable();
      children_.add(value.toStringUtf8());
    }

    public static final int COURSEID_FIELD_NUMBER = 2;
    private int courseId_;
    /**
     * <code>int32 courseId = 2;</code>
     * @return The courseId.
     */
    @java.lang.Override
    public int getCourseId() {
      return courseId_;
    }
    /**
     * <code>int32 courseId = 2;</code>
     * @param value The courseId to set.
     */
    private void setCourseId(int value) {
      
      courseId_ = value;
    }
    /**
     * <code>int32 courseId = 2;</code>
     */
    private void clearCourseId() {
      
      courseId_ = 0;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 3;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 3;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.String name_;
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 4;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 4;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 4;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int ORDER_FIELD_NUMBER = 5;
    private int order_;
    /**
     * <code>int32 order = 5;</code>
     * @return The order.
     */
    @java.lang.Override
    public int getOrder() {
      return order_;
    }
    /**
     * <code>int32 order = 5;</code>
     * @param value The order to set.
     */
    private void setOrder(int value) {
      
      order_ = value;
    }
    /**
     * <code>int32 order = 5;</code>
     */
    private void clearOrder() {
      
      order_ = 0;
    }

    public static final int PARENTCHAPTERID_FIELD_NUMBER = 6;
    private int parentChapterId_;
    /**
     * <code>int32 parentChapterId = 6;</code>
     * @return The parentChapterId.
     */
    @java.lang.Override
    public int getParentChapterId() {
      return parentChapterId_;
    }
    /**
     * <code>int32 parentChapterId = 6;</code>
     * @param value The parentChapterId to set.
     */
    private void setParentChapterId(int value) {
      
      parentChapterId_ = value;
    }
    /**
     * <code>int32 parentChapterId = 6;</code>
     */
    private void clearParentChapterId() {
      
      parentChapterId_ = 0;
    }

    public static final int USERCONTROLSETTOP_FIELD_NUMBER = 7;
    private boolean userControlSetTop_;
    /**
     * <code>bool userControlSetTop = 7;</code>
     * @return The userControlSetTop.
     */
    @java.lang.Override
    public boolean getUserControlSetTop() {
      return userControlSetTop_;
    }
    /**
     * <code>bool userControlSetTop = 7;</code>
     * @param value The userControlSetTop to set.
     */
    private void setUserControlSetTop(boolean value) {
      
      userControlSetTop_ = value;
    }
    /**
     * <code>bool userControlSetTop = 7;</code>
     */
    private void clearUserControlSetTop() {
      
      userControlSetTop_ = false;
    }

    public static final int VISIBLE_FIELD_NUMBER = 8;
    private int visible_;
    /**
     * <code>int32 visible = 8;</code>
     * @return The visible.
     */
    @java.lang.Override
    public int getVisible() {
      return visible_;
    }
    /**
     * <code>int32 visible = 8;</code>
     * @param value The visible to set.
     */
    private void setVisible(int value) {
      
      visible_ = value;
    }
    /**
     * <code>int32 visible = 8;</code>
     */
    private void clearVisible() {
      
      visible_ = 0;
    }

    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code ProjectTreePreferences.ProjectTreeBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean, Builder> implements
        // @@protoc_insertion_point(builder_implements:ProjectTreePreferences.ProjectTreeBean)
        com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBeanOrBuilder {
      // Construct using com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated string children = 1;</code>
       * @return A list containing the children.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getChildrenList() {
        return java.util.Collections.unmodifiableList(
            instance.getChildrenList());
      }
      /**
       * <code>repeated string children = 1;</code>
       * @return The count of children.
       */
      @java.lang.Override
      public int getChildrenCount() {
        return instance.getChildrenCount();
      }
      /**
       * <code>repeated string children = 1;</code>
       * @param index The index of the element to return.
       * @return The children at the given index.
       */
      @java.lang.Override
      public java.lang.String getChildren(int index) {
        return instance.getChildren(index);
      }
      /**
       * <code>repeated string children = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the children at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getChildrenBytes(int index) {
        return instance.getChildrenBytes(index);
      }
      /**
       * <code>repeated string children = 1;</code>
       * @param index The index to set the value at.
       * @param value The children to set.
       * @return This builder for chaining.
       */
      public Builder setChildren(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setChildren(index, value);
        return this;
      }
      /**
       * <code>repeated string children = 1;</code>
       * @param value The children to add.
       * @return This builder for chaining.
       */
      public Builder addChildren(
          java.lang.String value) {
        copyOnWrite();
        instance.addChildren(value);
        return this;
      }
      /**
       * <code>repeated string children = 1;</code>
       * @param values The children to add.
       * @return This builder for chaining.
       */
      public Builder addAllChildren(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllChildren(values);
        return this;
      }
      /**
       * <code>repeated string children = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChildren() {
        copyOnWrite();
        instance.clearChildren();
        return this;
      }
      /**
       * <code>repeated string children = 1;</code>
       * @param value The bytes of the children to add.
       * @return This builder for chaining.
       */
      public Builder addChildrenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addChildrenBytes(value);
        return this;
      }

      /**
       * <code>int32 courseId = 2;</code>
       * @return The courseId.
       */
      @java.lang.Override
      public int getCourseId() {
        return instance.getCourseId();
      }
      /**
       * <code>int32 courseId = 2;</code>
       * @param value The courseId to set.
       * @return This builder for chaining.
       */
      public Builder setCourseId(int value) {
        copyOnWrite();
        instance.setCourseId(value);
        return this;
      }
      /**
       * <code>int32 courseId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCourseId() {
        copyOnWrite();
        instance.clearCourseId();
        return this;
      }

      /**
       * <code>int32 id = 3;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 3;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string name = 4;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 4;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>int32 order = 5;</code>
       * @return The order.
       */
      @java.lang.Override
      public int getOrder() {
        return instance.getOrder();
      }
      /**
       * <code>int32 order = 5;</code>
       * @param value The order to set.
       * @return This builder for chaining.
       */
      public Builder setOrder(int value) {
        copyOnWrite();
        instance.setOrder(value);
        return this;
      }
      /**
       * <code>int32 order = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrder() {
        copyOnWrite();
        instance.clearOrder();
        return this;
      }

      /**
       * <code>int32 parentChapterId = 6;</code>
       * @return The parentChapterId.
       */
      @java.lang.Override
      public int getParentChapterId() {
        return instance.getParentChapterId();
      }
      /**
       * <code>int32 parentChapterId = 6;</code>
       * @param value The parentChapterId to set.
       * @return This builder for chaining.
       */
      public Builder setParentChapterId(int value) {
        copyOnWrite();
        instance.setParentChapterId(value);
        return this;
      }
      /**
       * <code>int32 parentChapterId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentChapterId() {
        copyOnWrite();
        instance.clearParentChapterId();
        return this;
      }

      /**
       * <code>bool userControlSetTop = 7;</code>
       * @return The userControlSetTop.
       */
      @java.lang.Override
      public boolean getUserControlSetTop() {
        return instance.getUserControlSetTop();
      }
      /**
       * <code>bool userControlSetTop = 7;</code>
       * @param value The userControlSetTop to set.
       * @return This builder for chaining.
       */
      public Builder setUserControlSetTop(boolean value) {
        copyOnWrite();
        instance.setUserControlSetTop(value);
        return this;
      }
      /**
       * <code>bool userControlSetTop = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserControlSetTop() {
        copyOnWrite();
        instance.clearUserControlSetTop();
        return this;
      }

      /**
       * <code>int32 visible = 8;</code>
       * @return The visible.
       */
      @java.lang.Override
      public int getVisible() {
        return instance.getVisible();
      }
      /**
       * <code>int32 visible = 8;</code>
       * @param value The visible to set.
       * @return This builder for chaining.
       */
      public Builder setVisible(int value) {
        copyOnWrite();
        instance.setVisible(value);
        return this;
      }
      /**
       * <code>int32 visible = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearVisible() {
        copyOnWrite();
        instance.clearVisible();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProjectTreePreferences.ProjectTreeBean)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "children_",
              "courseId_",
              "id_",
              "name_",
              "order_",
              "parentChapterId_",
              "userControlSetTop_",
              "visible_",
            };
            java.lang.String info =
                "\u0000\b\u0000\u0000\u0001\b\b\u0000\u0001\u0000\u0001\u021a\u0002\u0004\u0003\u0004" +
                "\u0004\u0208\u0005\u0004\u0006\u0004\u0007\u0007\b\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> parser = PARSER;
          if (parser == null) {
            synchronized (com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ProjectTreePreferences.ProjectTreeBean)
    private static final com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean DEFAULT_INSTANCE;
    static {
      ProjectTreeBean defaultInstance = new ProjectTreeBean();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ProjectTreeBean.class, defaultInstance);
    }

    public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ProjectTreeBean> PARSER;

    public static com.google.protobuf.Parser<ProjectTreeBean> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int PROJECTTREEBEAN_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> projectTreeBean_;
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> getProjectTreeBeanList() {
    return projectTreeBean_;
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  public java.util.List<? extends com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBeanOrBuilder> 
      getProjectTreeBeanOrBuilderList() {
    return projectTreeBean_;
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  @java.lang.Override
  public int getProjectTreeBeanCount() {
    return projectTreeBean_.size();
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  @java.lang.Override
  public com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean getProjectTreeBean(int index) {
    return projectTreeBean_.get(index);
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  public com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBeanOrBuilder getProjectTreeBeanOrBuilder(
      int index) {
    return projectTreeBean_.get(index);
  }
  private void ensureProjectTreeBeanIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> tmp = projectTreeBean_;
    if (!tmp.isModifiable()) {
      projectTreeBean_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  private void setProjectTreeBean(
      int index, com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean value) {
    value.getClass();
  ensureProjectTreeBeanIsMutable();
    projectTreeBean_.set(index, value);
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  private void addProjectTreeBean(com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean value) {
    value.getClass();
  ensureProjectTreeBeanIsMutable();
    projectTreeBean_.add(value);
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  private void addProjectTreeBean(
      int index, com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean value) {
    value.getClass();
  ensureProjectTreeBeanIsMutable();
    projectTreeBean_.add(index, value);
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  private void addAllProjectTreeBean(
      java.lang.Iterable<? extends com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> values) {
    ensureProjectTreeBeanIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, projectTreeBean_);
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  private void clearProjectTreeBean() {
    projectTreeBean_ = emptyProtobufList();
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  private void removeProjectTreeBean(int index) {
    ensureProjectTreeBeanIsMutable();
    projectTreeBean_.remove(index);
  }

  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.linwei.cams.datastore.protobuf.ProjectTreePreferences prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ProjectTreePreferences}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.linwei.cams.datastore.protobuf.ProjectTreePreferences, Builder> implements
      // @@protoc_insertion_point(builder_implements:ProjectTreePreferences)
      com.linwei.cams.datastore.protobuf.ProjectTreePreferencesOrBuilder {
    // Construct using com.linwei.cams.datastore.protobuf.ProjectTreePreferences.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> getProjectTreeBeanList() {
      return java.util.Collections.unmodifiableList(
          instance.getProjectTreeBeanList());
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    @java.lang.Override
    public int getProjectTreeBeanCount() {
      return instance.getProjectTreeBeanCount();
    }/**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    @java.lang.Override
    public com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean getProjectTreeBean(int index) {
      return instance.getProjectTreeBean(index);
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder setProjectTreeBean(
        int index, com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean value) {
      copyOnWrite();
      instance.setProjectTreeBean(index, value);
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder setProjectTreeBean(
        int index, com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean.Builder builderForValue) {
      copyOnWrite();
      instance.setProjectTreeBean(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder addProjectTreeBean(com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean value) {
      copyOnWrite();
      instance.addProjectTreeBean(value);
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder addProjectTreeBean(
        int index, com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean value) {
      copyOnWrite();
      instance.addProjectTreeBean(index, value);
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder addProjectTreeBean(
        com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean.Builder builderForValue) {
      copyOnWrite();
      instance.addProjectTreeBean(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder addProjectTreeBean(
        int index, com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean.Builder builderForValue) {
      copyOnWrite();
      instance.addProjectTreeBean(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder addAllProjectTreeBean(
        java.lang.Iterable<? extends com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> values) {
      copyOnWrite();
      instance.addAllProjectTreeBean(values);
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder clearProjectTreeBean() {
      copyOnWrite();
      instance.clearProjectTreeBean();
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
     */
    public Builder removeProjectTreeBean(int index) {
      copyOnWrite();
      instance.removeProjectTreeBean(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ProjectTreePreferences)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.linwei.cams.datastore.protobuf.ProjectTreePreferences();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "projectTreeBean_",
            com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.linwei.cams.datastore.protobuf.ProjectTreePreferences> parser = PARSER;
        if (parser == null) {
          synchronized (com.linwei.cams.datastore.protobuf.ProjectTreePreferences.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.linwei.cams.datastore.protobuf.ProjectTreePreferences>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ProjectTreePreferences)
  private static final com.linwei.cams.datastore.protobuf.ProjectTreePreferences DEFAULT_INSTANCE;
  static {
    ProjectTreePreferences defaultInstance = new ProjectTreePreferences();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ProjectTreePreferences.class, defaultInstance);
  }

  public static com.linwei.cams.datastore.protobuf.ProjectTreePreferences getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProjectTreePreferences> PARSER;

  public static com.google.protobuf.Parser<ProjectTreePreferences> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

