// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projecttree.proto

package com.linwei.cams.datastore.protobuf;

public interface ProjectTreePreferencesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProjectTreePreferences)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  java.util.List<com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean> 
      getProjectTreeBeanList();
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  com.linwei.cams.datastore.protobuf.ProjectTreePreferences.ProjectTreeBean getProjectTreeBean(int index);
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>repeated .ProjectTreePreferences.ProjectTreeBean projectTreeBean = 1;</code>
   */
  int getProjectTreeBeanCount();
}
