// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinfo.proto

package com.linwei.cams.datastore.protobuf;

/**
 * Protobuf type {@code UserInfoPreferences}
 */
public  final class UserInfoPreferences extends
    com.google.protobuf.GeneratedMessageLite<
        UserInfoPreferences, UserInfoPreferences.Builder> implements
    // @@protoc_insertion_point(message_implements:UserInfoPreferences)
    UserInfoPreferencesOrBuilder {
  private UserInfoPreferences() {
    email_ = "";
    icon_ = "";
    id_ = "";
    password_ = "";
    token_ = "";
    type_ = "";
    username_ = "";
    chapterTops_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    collectIds_ = emptyIntList();
    coinCount_ = "";
    rank_ = "";
    userId_ = "";
    reason_ = "";
    desc_ = "";
    date_ = "";
  }
  public static final int EMAIL_FIELD_NUMBER = 1;
  private java.lang.String email_;
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string email = 1;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    return email_;
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(email_);
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string email = 1;</code>
   * @param value The email to set.
   */
  private void setEmail(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    email_ = value;
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string email = 1;</code>
   */
  private void clearEmail() {
    
    email_ = getDefaultInstance().getEmail();
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string email = 1;</code>
   * @param value The bytes for email to set.
   */
  private void setEmailBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    email_ = value.toStringUtf8();
    
  }

  public static final int ICON_FIELD_NUMBER = 2;
  private java.lang.String icon_;
  /**
   * <code>string icon = 2;</code>
   * @return The icon.
   */
  @java.lang.Override
  public java.lang.String getIcon() {
    return icon_;
  }
  /**
   * <code>string icon = 2;</code>
   * @return The bytes for icon.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIconBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(icon_);
  }
  /**
   * <code>string icon = 2;</code>
   * @param value The icon to set.
   */
  private void setIcon(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    icon_ = value;
  }
  /**
   * <code>string icon = 2;</code>
   */
  private void clearIcon() {
    
    icon_ = getDefaultInstance().getIcon();
  }
  /**
   * <code>string icon = 2;</code>
   * @param value The bytes for icon to set.
   */
  private void setIconBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    icon_ = value.toStringUtf8();
    
  }

  public static final int ID_FIELD_NUMBER = 3;
  private java.lang.String id_;
  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 3;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <code>string id = 3;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 3;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  private java.lang.String password_;
  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    return password_;
  }
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(password_);
  }
  /**
   * <code>string password = 4;</code>
   * @param value The password to set.
   */
  private void setPassword(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    password_ = value;
  }
  /**
   * <code>string password = 4;</code>
   */
  private void clearPassword() {
    
    password_ = getDefaultInstance().getPassword();
  }
  /**
   * <code>string password = 4;</code>
   * @param value The bytes for password to set.
   */
  private void setPasswordBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    password_ = value.toStringUtf8();
    
  }

  public static final int TOKEN_FIELD_NUMBER = 5;
  private java.lang.String token_;
  /**
   * <code>string token = 5;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    return token_;
  }
  /**
   * <code>string token = 5;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(token_);
  }
  /**
   * <code>string token = 5;</code>
   * @param value The token to set.
   */
  private void setToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    token_ = value;
  }
  /**
   * <code>string token = 5;</code>
   */
  private void clearToken() {
    
    token_ = getDefaultInstance().getToken();
  }
  /**
   * <code>string token = 5;</code>
   * @param value The bytes for token to set.
   */
  private void setTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    token_ = value.toStringUtf8();
    
  }

  public static final int TYPE_FIELD_NUMBER = 6;
  private java.lang.String type_;
  /**
   * <code>string type = 6;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    return type_;
  }
  /**
   * <code>string type = 6;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(type_);
  }
  /**
   * <code>string type = 6;</code>
   * @param value The type to set.
   */
  private void setType(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    type_ = value;
  }
  /**
   * <code>string type = 6;</code>
   */
  private void clearType() {
    
    type_ = getDefaultInstance().getType();
  }
  /**
   * <code>string type = 6;</code>
   * @param value The bytes for type to set.
   */
  private void setTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    type_ = value.toStringUtf8();
    
  }

  public static final int USERNAME_FIELD_NUMBER = 7;
  private java.lang.String username_;
  /**
   * <code>string username = 7;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 7;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 7;</code>
   * @param value The username to set.
   */
  private void setUsername(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    username_ = value;
  }
  /**
   * <code>string username = 7;</code>
   */
  private void clearUsername() {
    
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 7;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();
    
  }

  public static final int CHAPTERTOPS_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> chapterTops_;
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @return A list containing the chapterTops.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getChapterTopsList() {
    return chapterTops_;
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @return The count of chapterTops.
   */
  @java.lang.Override
  public int getChapterTopsCount() {
    return chapterTops_.size();
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param index The index of the element to return.
   * @return The chapterTops at the given index.
   */
  @java.lang.Override
  public java.lang.String getChapterTops(int index) {
    return chapterTops_.get(index);
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the chapterTops at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChapterTopsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        chapterTops_.get(index));
  }
  private void ensureChapterTopsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        chapterTops_;  if (!tmp.isModifiable()) {
      chapterTops_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param index The index to set the value at.
   * @param value The chapterTops to set.
   */
  private void setChapterTops(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureChapterTopsIsMutable();
    chapterTops_.set(index, value);
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param value The chapterTops to add.
   */
  private void addChapterTops(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureChapterTopsIsMutable();
    chapterTops_.add(value);
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param values The chapterTops to add.
   */
  private void addAllChapterTops(
      java.lang.Iterable<java.lang.String> values) {
    ensureChapterTopsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, chapterTops_);
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   */
  private void clearChapterTops() {
    chapterTops_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param value The bytes of the chapterTops to add.
   */
  private void addChapterTopsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureChapterTopsIsMutable();
    chapterTops_.add(value.toStringUtf8());
  }

  public static final int COLLECTIDS_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.IntList collectIds_;
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @return A list containing the collectIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getCollectIdsList() {
    return collectIds_;
  }
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @return The count of collectIds.
   */
  @java.lang.Override
  public int getCollectIdsCount() {
    return collectIds_.size();
  }
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @param index The index of the element to return.
   * @return The collectIds at the given index.
   */
  @java.lang.Override
  public int getCollectIds(int index) {
    return collectIds_.getInt(index);
  }
  private int collectIdsMemoizedSerializedSize = -1;
  private void ensureCollectIdsIsMutable() {
    com.google.protobuf.Internal.IntList tmp = collectIds_;
    if (!tmp.isModifiable()) {
      collectIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @param index The index to set the value at.
   * @param value The collectIds to set.
   */
  private void setCollectIds(
      int index, int value) {
    ensureCollectIdsIsMutable();
    collectIds_.setInt(index, value);
  }
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @param value The collectIds to add.
   */
  private void addCollectIds(int value) {
    ensureCollectIdsIsMutable();
    collectIds_.addInt(value);
  }
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @param values The collectIds to add.
   */
  private void addAllCollectIds(
      java.lang.Iterable<? extends java.lang.Integer> values) {
    ensureCollectIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, collectIds_);
  }
  /**
   * <code>repeated int32 collectIds = 9;</code>
   */
  private void clearCollectIds() {
    collectIds_ = emptyIntList();
  }

  public static final int COINCOUNT_FIELD_NUMBER = 10;
  private java.lang.String coinCount_;
  /**
   * <code>string coinCount = 10;</code>
   * @return The coinCount.
   */
  @java.lang.Override
  public java.lang.String getCoinCount() {
    return coinCount_;
  }
  /**
   * <code>string coinCount = 10;</code>
   * @return The bytes for coinCount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCoinCountBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(coinCount_);
  }
  /**
   * <code>string coinCount = 10;</code>
   * @param value The coinCount to set.
   */
  private void setCoinCount(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    coinCount_ = value;
  }
  /**
   * <code>string coinCount = 10;</code>
   */
  private void clearCoinCount() {
    
    coinCount_ = getDefaultInstance().getCoinCount();
  }
  /**
   * <code>string coinCount = 10;</code>
   * @param value The bytes for coinCount to set.
   */
  private void setCoinCountBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    coinCount_ = value.toStringUtf8();
    
  }

  public static final int LEVEL_FIELD_NUMBER = 11;
  private int level_;
  /**
   * <code>int32 level = 11;</code>
   * @return The level.
   */
  @java.lang.Override
  public int getLevel() {
    return level_;
  }
  /**
   * <code>int32 level = 11;</code>
   * @param value The level to set.
   */
  private void setLevel(int value) {
    
    level_ = value;
  }
  /**
   * <code>int32 level = 11;</code>
   */
  private void clearLevel() {
    
    level_ = 0;
  }

  public static final int RANK_FIELD_NUMBER = 12;
  private java.lang.String rank_;
  /**
   * <code>string rank = 12;</code>
   * @return The rank.
   */
  @java.lang.Override
  public java.lang.String getRank() {
    return rank_;
  }
  /**
   * <code>string rank = 12;</code>
   * @return The bytes for rank.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRankBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(rank_);
  }
  /**
   * <code>string rank = 12;</code>
   * @param value The rank to set.
   */
  private void setRank(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    rank_ = value;
  }
  /**
   * <code>string rank = 12;</code>
   */
  private void clearRank() {
    
    rank_ = getDefaultInstance().getRank();
  }
  /**
   * <code>string rank = 12;</code>
   * @param value The bytes for rank to set.
   */
  private void setRankBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    rank_ = value.toStringUtf8();
    
  }

  public static final int USERID_FIELD_NUMBER = 13;
  private java.lang.String userId_;
  /**
   * <code>string userId = 13;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <code>string userId = 13;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <code>string userId = 13;</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userId_ = value;
  }
  /**
   * <code>string userId = 13;</code>
   */
  private void clearUserId() {
    
    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <code>string userId = 13;</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();
    
  }

  public static final int REASON_FIELD_NUMBER = 14;
  private java.lang.String reason_;
  /**
   * <code>string reason = 14;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <code>string reason = 14;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <code>string reason = 14;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reason_ = value;
  }
  /**
   * <code>string reason = 14;</code>
   */
  private void clearReason() {
    
    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <code>string reason = 14;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();
    
  }

  public static final int DESC_FIELD_NUMBER = 15;
  private java.lang.String desc_;
  /**
   * <code>string desc = 15;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    return desc_;
  }
  /**
   * <code>string desc = 15;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(desc_);
  }
  /**
   * <code>string desc = 15;</code>
   * @param value The desc to set.
   */
  private void setDesc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    desc_ = value;
  }
  /**
   * <code>string desc = 15;</code>
   */
  private void clearDesc() {
    
    desc_ = getDefaultInstance().getDesc();
  }
  /**
   * <code>string desc = 15;</code>
   * @param value The bytes for desc to set.
   */
  private void setDescBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    desc_ = value.toStringUtf8();
    
  }

  public static final int DATE_FIELD_NUMBER = 16;
  private java.lang.String date_;
  /**
   * <code>string date = 16;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    return date_;
  }
  /**
   * <code>string date = 16;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(date_);
  }
  /**
   * <code>string date = 16;</code>
   * @param value The date to set.
   */
  private void setDate(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    date_ = value;
  }
  /**
   * <code>string date = 16;</code>
   */
  private void clearDate() {
    
    date_ = getDefaultInstance().getDate();
  }
  /**
   * <code>string date = 16;</code>
   * @param value The bytes for date to set.
   */
  private void setDateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    date_ = value.toStringUtf8();
    
  }

  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.linwei.cams.datastore.protobuf.UserInfoPreferences prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code UserInfoPreferences}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.linwei.cams.datastore.protobuf.UserInfoPreferences, Builder> implements
      // @@protoc_insertion_point(builder_implements:UserInfoPreferences)
      com.linwei.cams.datastore.protobuf.UserInfoPreferencesOrBuilder {
    // Construct using com.linwei.cams.datastore.protobuf.UserInfoPreferences.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string email = 1;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return instance.getEmail();
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string email = 1;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return instance.getEmailBytes();
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string email = 1;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      copyOnWrite();
      instance.setEmail(value);
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string email = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      copyOnWrite();
      instance.clearEmail();
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string email = 1;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEmailBytes(value);
      return this;
    }

    /**
     * <code>string icon = 2;</code>
     * @return The icon.
     */
    @java.lang.Override
    public java.lang.String getIcon() {
      return instance.getIcon();
    }
    /**
     * <code>string icon = 2;</code>
     * @return The bytes for icon.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIconBytes() {
      return instance.getIconBytes();
    }
    /**
     * <code>string icon = 2;</code>
     * @param value The icon to set.
     * @return This builder for chaining.
     */
    public Builder setIcon(
        java.lang.String value) {
      copyOnWrite();
      instance.setIcon(value);
      return this;
    }
    /**
     * <code>string icon = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIcon() {
      copyOnWrite();
      instance.clearIcon();
      return this;
    }
    /**
     * <code>string icon = 2;</code>
     * @param value The bytes for icon to set.
     * @return This builder for chaining.
     */
    public Builder setIconBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIconBytes(value);
      return this;
    }

    /**
     * <code>string id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 3;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 3;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      return instance.getPassword();
    }
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return instance.getPasswordBytes();
    }
    /**
     * <code>string password = 4;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      copyOnWrite();
      instance.setPassword(value);
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      copyOnWrite();
      instance.clearPassword();
      return this;
    }
    /**
     * <code>string password = 4;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPasswordBytes(value);
      return this;
    }

    /**
     * <code>string token = 5;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      return instance.getToken();
    }
    /**
     * <code>string token = 5;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return instance.getTokenBytes();
    }
    /**
     * <code>string token = 5;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setToken(value);
      return this;
    }
    /**
     * <code>string token = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      copyOnWrite();
      instance.clearToken();
      return this;
    }
    /**
     * <code>string token = 5;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenBytes(value);
      return this;
    }

    /**
     * <code>string type = 6;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      return instance.getType();
    }
    /**
     * <code>string type = 6;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return instance.getTypeBytes();
    }
    /**
     * <code>string type = 6;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <code>string type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }
    /**
     * <code>string type = 6;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTypeBytes(value);
      return this;
    }

    /**
     * <code>string username = 7;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 7;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 7;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 7;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>repeated string chapterTops = 8;</code>
     * @return A list containing the chapterTops.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getChapterTopsList() {
      return java.util.Collections.unmodifiableList(
          instance.getChapterTopsList());
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @return The count of chapterTops.
     */
    @java.lang.Override
    public int getChapterTopsCount() {
      return instance.getChapterTopsCount();
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @param index The index of the element to return.
     * @return The chapterTops at the given index.
     */
    @java.lang.Override
    public java.lang.String getChapterTops(int index) {
      return instance.getChapterTops(index);
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the chapterTops at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChapterTopsBytes(int index) {
      return instance.getChapterTopsBytes(index);
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @param index The index to set the value at.
     * @param value The chapterTops to set.
     * @return This builder for chaining.
     */
    public Builder setChapterTops(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setChapterTops(index, value);
      return this;
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @param value The chapterTops to add.
     * @return This builder for chaining.
     */
    public Builder addChapterTops(
        java.lang.String value) {
      copyOnWrite();
      instance.addChapterTops(value);
      return this;
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @param values The chapterTops to add.
     * @return This builder for chaining.
     */
    public Builder addAllChapterTops(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllChapterTops(values);
      return this;
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearChapterTops() {
      copyOnWrite();
      instance.clearChapterTops();
      return this;
    }
    /**
     * <code>repeated string chapterTops = 8;</code>
     * @param value The bytes of the chapterTops to add.
     * @return This builder for chaining.
     */
    public Builder addChapterTopsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addChapterTopsBytes(value);
      return this;
    }

    /**
     * <code>repeated int32 collectIds = 9;</code>
     * @return A list containing the collectIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getCollectIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getCollectIdsList());
    }
    /**
     * <code>repeated int32 collectIds = 9;</code>
     * @return The count of collectIds.
     */
    @java.lang.Override
    public int getCollectIdsCount() {
      return instance.getCollectIdsCount();
    }
    /**
     * <code>repeated int32 collectIds = 9;</code>
     * @param index The index of the element to return.
     * @return The collectIds at the given index.
     */
    @java.lang.Override
    public int getCollectIds(int index) {
      return instance.getCollectIds(index);
    }
    /**
     * <code>repeated int32 collectIds = 9;</code>
     * @param value The collectIds to set.
     * @return This builder for chaining.
     */
    public Builder setCollectIds(
        int index, int value) {
      copyOnWrite();
      instance.setCollectIds(index, value);
      return this;
    }
    /**
     * <code>repeated int32 collectIds = 9;</code>
     * @param value The collectIds to add.
     * @return This builder for chaining.
     */
    public Builder addCollectIds(int value) {
      copyOnWrite();
      instance.addCollectIds(value);
      return this;
    }
    /**
     * <code>repeated int32 collectIds = 9;</code>
     * @param values The collectIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllCollectIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllCollectIds(values);
      return this;
    }
    /**
     * <code>repeated int32 collectIds = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectIds() {
      copyOnWrite();
      instance.clearCollectIds();
      return this;
    }

    /**
     * <code>string coinCount = 10;</code>
     * @return The coinCount.
     */
    @java.lang.Override
    public java.lang.String getCoinCount() {
      return instance.getCoinCount();
    }
    /**
     * <code>string coinCount = 10;</code>
     * @return The bytes for coinCount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoinCountBytes() {
      return instance.getCoinCountBytes();
    }
    /**
     * <code>string coinCount = 10;</code>
     * @param value The coinCount to set.
     * @return This builder for chaining.
     */
    public Builder setCoinCount(
        java.lang.String value) {
      copyOnWrite();
      instance.setCoinCount(value);
      return this;
    }
    /**
     * <code>string coinCount = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoinCount() {
      copyOnWrite();
      instance.clearCoinCount();
      return this;
    }
    /**
     * <code>string coinCount = 10;</code>
     * @param value The bytes for coinCount to set.
     * @return This builder for chaining.
     */
    public Builder setCoinCountBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCoinCountBytes(value);
      return this;
    }

    /**
     * <code>int32 level = 11;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return instance.getLevel();
    }
    /**
     * <code>int32 level = 11;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {
      copyOnWrite();
      instance.setLevel(value);
      return this;
    }
    /**
     * <code>int32 level = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      copyOnWrite();
      instance.clearLevel();
      return this;
    }

    /**
     * <code>string rank = 12;</code>
     * @return The rank.
     */
    @java.lang.Override
    public java.lang.String getRank() {
      return instance.getRank();
    }
    /**
     * <code>string rank = 12;</code>
     * @return The bytes for rank.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRankBytes() {
      return instance.getRankBytes();
    }
    /**
     * <code>string rank = 12;</code>
     * @param value The rank to set.
     * @return This builder for chaining.
     */
    public Builder setRank(
        java.lang.String value) {
      copyOnWrite();
      instance.setRank(value);
      return this;
    }
    /**
     * <code>string rank = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRank() {
      copyOnWrite();
      instance.clearRank();
      return this;
    }
    /**
     * <code>string rank = 12;</code>
     * @param value The bytes for rank to set.
     * @return This builder for chaining.
     */
    public Builder setRankBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRankBytes(value);
      return this;
    }

    /**
     * <code>string userId = 13;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>string userId = 13;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <code>string userId = 13;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>string userId = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <code>string userId = 13;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <code>string reason = 14;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <code>string reason = 14;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <code>string reason = 14;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>string reason = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <code>string reason = 14;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    /**
     * <code>string desc = 15;</code>
     * @return The desc.
     */
    @java.lang.Override
    public java.lang.String getDesc() {
      return instance.getDesc();
    }
    /**
     * <code>string desc = 15;</code>
     * @return The bytes for desc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      return instance.getDescBytes();
    }
    /**
     * <code>string desc = 15;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      copyOnWrite();
      instance.setDesc(value);
      return this;
    }
    /**
     * <code>string desc = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      copyOnWrite();
      instance.clearDesc();
      return this;
    }
    /**
     * <code>string desc = 15;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescBytes(value);
      return this;
    }

    /**
     * <code>string date = 16;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      return instance.getDate();
    }
    /**
     * <code>string date = 16;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      return instance.getDateBytes();
    }
    /**
     * <code>string date = 16;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      copyOnWrite();
      instance.setDate(value);
      return this;
    }
    /**
     * <code>string date = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      copyOnWrite();
      instance.clearDate();
      return this;
    }
    /**
     * <code>string date = 16;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDateBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UserInfoPreferences)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.linwei.cams.datastore.protobuf.UserInfoPreferences();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "email_",
            "icon_",
            "id_",
            "password_",
            "token_",
            "type_",
            "username_",
            "chapterTops_",
            "collectIds_",
            "coinCount_",
            "level_",
            "rank_",
            "userId_",
            "reason_",
            "desc_",
            "date_",
          };
          java.lang.String info =
              "\u0000\u0010\u0000\u0000\u0001\u0010\u0010\u0000\u0002\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\u021a\t\'\n\u0208" +
              "\u000b\u0004\f\u0208\r\u0208\u000e\u0208\u000f\u0208\u0010\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.linwei.cams.datastore.protobuf.UserInfoPreferences> parser = PARSER;
        if (parser == null) {
          synchronized (com.linwei.cams.datastore.protobuf.UserInfoPreferences.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.linwei.cams.datastore.protobuf.UserInfoPreferences>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:UserInfoPreferences)
  private static final com.linwei.cams.datastore.protobuf.UserInfoPreferences DEFAULT_INSTANCE;
  static {
    UserInfoPreferences defaultInstance = new UserInfoPreferences();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserInfoPreferences.class, defaultInstance);
  }

  public static com.linwei.cams.datastore.protobuf.UserInfoPreferences getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserInfoPreferences> PARSER;

  public static com.google.protobuf.Parser<UserInfoPreferences> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

