// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: language.proto

package com.linwei.cams.datastore.protobuf;

/**
 * Protobuf type {@code LanguagePreferences}
 */
public  final class LanguagePreferences extends
    com.google.protobuf.GeneratedMessageLite<
        LanguagePreferences, LanguagePreferences.Builder> implements
    // @@protoc_insertion_point(message_implements:LanguagePreferences)
    LanguagePreferencesOrBuilder {
  private LanguagePreferences() {
    locale_ = "";
  }
  public static final int LOCALE_FIELD_NUMBER = 1;
  private java.lang.String locale_;
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string locale = 1;</code>
   * @return The locale.
   */
  @java.lang.Override
  public java.lang.String getLocale() {
    return locale_;
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string locale = 1;</code>
   * @return The bytes for locale.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocaleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(locale_);
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string locale = 1;</code>
   * @param value The locale to set.
   */
  private void setLocale(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    locale_ = value;
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string locale = 1;</code>
   */
  private void clearLocale() {
    
    locale_ = getDefaultInstance().getLocale();
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string locale = 1;</code>
   * @param value The bytes for locale to set.
   */
  private void setLocaleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    locale_ = value.toStringUtf8();
    
  }

  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.linwei.cams.datastore.protobuf.LanguagePreferences parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.linwei.cams.datastore.protobuf.LanguagePreferences prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code LanguagePreferences}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.linwei.cams.datastore.protobuf.LanguagePreferences, Builder> implements
      // @@protoc_insertion_point(builder_implements:LanguagePreferences)
      com.linwei.cams.datastore.protobuf.LanguagePreferencesOrBuilder {
    // Construct using com.linwei.cams.datastore.protobuf.LanguagePreferences.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string locale = 1;</code>
     * @return The locale.
     */
    @java.lang.Override
    public java.lang.String getLocale() {
      return instance.getLocale();
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string locale = 1;</code>
     * @return The bytes for locale.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      return instance.getLocaleBytes();
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string locale = 1;</code>
     * @param value The locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocale(
        java.lang.String value) {
      copyOnWrite();
      instance.setLocale(value);
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string locale = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocale() {
      copyOnWrite();
      instance.clearLocale();
      return this;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string locale = 1;</code>
     * @param value The bytes for locale to set.
     * @return This builder for chaining.
     */
    public Builder setLocaleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLocaleBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:LanguagePreferences)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.linwei.cams.datastore.protobuf.LanguagePreferences();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "locale_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.linwei.cams.datastore.protobuf.LanguagePreferences> parser = PARSER;
        if (parser == null) {
          synchronized (com.linwei.cams.datastore.protobuf.LanguagePreferences.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.linwei.cams.datastore.protobuf.LanguagePreferences>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:LanguagePreferences)
  private static final com.linwei.cams.datastore.protobuf.LanguagePreferences DEFAULT_INSTANCE;
  static {
    LanguagePreferences defaultInstance = new LanguagePreferences();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LanguagePreferences.class, defaultInstance);
  }

  public static com.linwei.cams.datastore.protobuf.LanguagePreferences getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LanguagePreferences> PARSER;

  public static com.google.protobuf.Parser<LanguagePreferences> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

