// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projecttree.proto

package com.linwei.cams.datastore.protobuf;

public final class Projecttree {
  private Projecttree() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
