// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinfo.proto

package com.linwei.cams.datastore.protobuf;

public interface UserInfoPreferencesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserInfoPreferences)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string icon = 2;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <code>string icon = 2;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string token = 5;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 5;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string type = 6;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 6;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string username = 7;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 7;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>repeated string chapterTops = 8;</code>
   * @return A list containing the chapterTops.
   */
  java.util.List<java.lang.String>
      getChapterTopsList();
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @return The count of chapterTops.
   */
  int getChapterTopsCount();
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param index The index of the element to return.
   * @return The chapterTops at the given index.
   */
  java.lang.String getChapterTops(int index);
  /**
   * <code>repeated string chapterTops = 8;</code>
   * @param index The index of the element to return.
   * @return The chapterTops at the given index.
   */
  com.google.protobuf.ByteString
      getChapterTopsBytes(int index);

  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @return A list containing the collectIds.
   */
  java.util.List<java.lang.Integer> getCollectIdsList();
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @return The count of collectIds.
   */
  int getCollectIdsCount();
  /**
   * <code>repeated int32 collectIds = 9;</code>
   * @param index The index of the element to return.
   * @return The collectIds at the given index.
   */
  int getCollectIds(int index);

  /**
   * <code>string coinCount = 10;</code>
   * @return The coinCount.
   */
  java.lang.String getCoinCount();
  /**
   * <code>string coinCount = 10;</code>
   * @return The bytes for coinCount.
   */
  com.google.protobuf.ByteString
      getCoinCountBytes();

  /**
   * <code>int32 level = 11;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>string rank = 12;</code>
   * @return The rank.
   */
  java.lang.String getRank();
  /**
   * <code>string rank = 12;</code>
   * @return The bytes for rank.
   */
  com.google.protobuf.ByteString
      getRankBytes();

  /**
   * <code>string userId = 13;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 13;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string reason = 14;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 14;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>string desc = 15;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 15;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>string date = 16;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 16;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
